# File: azure-pipelines.yml
variables: 
- group: 'cdk_pipelines_serverless_deployments'


resources:
  repositories:
    - repository: cdk_pipelines
      type: git
      name: DevSecOps/cdk_pipelines
trigger:
- master

pool:
  vmImage: ubuntu-latest


stages:
- template: templates/ci_cd.yaml@cdk_pipelines  # Template reference

  parameters:
    Project: chatapp_read_message
    Listlambdas: 
      - SaveMessage
    AppPath: app
    Language: c#
    Action: destroy
    
    