#Build steps
# SAST for IaC

parameters:
- name: ServiceConnection
  type: string
  default: DevSecOpsServelessDeployment

- name: RegionName
  type: string
  default: us-east-2

- name: Project
  type: string
  default: DevSecOpsServelessDeployment

- name: CDKPath
  type: string
  default: .


- name: Environment
  type: string
  default: dev

- name: Language
  type: string
  default: python

- name:  AppPath
  type: string
  default: lambdas

- name:  PrivateRepository
  type: boolean
  default: false

- name:  AzureCustomFeed
  type: string
  default: a3dfeb18-d0fc-4033-99ae-50b8d724527b

- name: Listlambdas
  type: object
  default:
  - ReadMessage
  - SaveReadMessage


steps:
# dotnet
- ${{ if eq(parameters.Language, 'c#') }}:
  - script: |
      echo  'Build for environment Account - ' $(${{ parameters.Environment }}_account) 'Region-' $(${{ parameters.Environment }}_region)
      dotnet build src
    displayName: 'BuildDotnetProject'
    workingDirectory: ${{ parameters.CDKPath }}
    env:
      CDK_DEPLOY_ACCOUNT: $(${{ parameters.Environment }}_account)
      CDK_DEPLOY_REGION:  $(${{ parameters.Environment }}_region)
    #Compile app for serveless projects
  - ${{ each value in parameters.Listlambdas }}:
    - script: | 
        echo ${{ value }} 
        dotnet build src/${{ parameters.AppPath }}/${{ value }}/src/${{ value }}/    
      displayName: 'Build Lambdas'
# python
- ${{ if eq(parameters.Language, 'python') }}:
  - script: |
      echo  'Build for environment Account Using Python - ' $(${{ parameters.Environment }}_account) 'Region-' $(${{ parameters.Environment }}_region)
      pip install -r requirements.txt
    displayName: 'BuildPythonProject'
    workingDirectory: ${{ parameters.CDKPath }}

    env:
      CDK_DEPLOY_ACCOUNT: $(${{ parameters.Environment }}_account)
      CDK_DEPLOY_REGION:  $(${{ parameters.Environment }}_region)
# typescript
- ${{ if eq(parameters.Language, 'typescript') }}:
  - ${{ if eq(parameters.PrivateRepository, true) }}:
    - task: Npm@1
      inputs:
        command: 'install'
        verbose: true
        customRegistry: 'useFeed'
        customFeed: ${{ parameters.AzureCustomFeed }}
        workingDirectory: ${{ parameters.CDKPath }}
  - script: |
      echo  'Build for environment Account Using typescript - ' $(${{ parameters.Environment }}_account) 'Region-' $(${{ parameters.Environment }}_region)
      npm install
      npm run build # compile ts to js
      npm run test # perform jest unit tests
    displayName: 'BuildTypescriptProject'
    workingDirectory: ${{ parameters.CDKPath }}
    env:
      CDK_DEPLOY_ACCOUNT: $(${{ parameters.Environment }}_account)
      CDK_DEPLOY_REGION:  $(${{ parameters.Environment }}_region)

- script: |
    cdk synth 
    checkov -d cdk.out/ -o junitxml --output-file-path . -s #-s flag use soft mode
  displayName: 'SASTIaC'
  workingDirectory: ${{ parameters.CDKPath }}
      
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit' # 'JUnit' | 'NUnit' | 'VSTest' | 'XUnit' | 'CTest'. Alias: testRunner. Required. Test result format. Default: JUnit.
    testResultsFiles: '**/results_junitxml.xml'
    mergeTestResults: true
    failTaskOnFailedTests: false
    testRunTitle: 'SAST IaC Checkov scan'
  condition: 'always()'



- task: AWSShellScript@1
  inputs:
    awsCredentials: ${{ parameters.ServiceConnection }}
    regionName: ${{ parameters.RegionName }}
    scriptType: 'inline'
    inlineScript: |      
     
      echo  'Diff for environment Account - ' $(${{ parameters.Environment }}_account) 'Region-' $(${{ parameters.Environment }}_region)
      
      cdk diff
    displayName: 'CDK Diff'
    workingDirectory: ${{ parameters.CDKPath }}
  env:
    CDK_DEPLOY_ACCOUNT: $(${{ parameters.Environment }}_account)
    CDK_DEPLOY_REGION:  $(${{ parameters.Environment }}_region)
# Publish Package
- task: PublishPipelineArtifact@1
  displayName: PublishArtifact
  inputs:
    targetPath: '$(Build.SourcesDirectory)'
    artifactName: ${{ parameters.Project }}
  workingDirectory: ${{ parameters.CDKPath }}