# CDK Pipeline

parameters:
- name: Listlambdas
  type: object
  default:
  - ReadMessage
  - SaveReadMessage

- name: ServiceConnection
  type: string
  default: DevSecOpsServelessDeployment

- name: RegionName
  type: string
  default: us-east-2

- name:  AppPath
  type: string
  default: lambdas

- name: Project
  type: string
  default: DevSecOpsServelessDeployment

- name: Environment
  type: string
  default: dev

- name: OnDemandTestEnv
  type: boolean
  default: false

- name: Language
  type: string
  default: python

- name: CDKPath
  type: string
  default: .

- name:  Action
  type: string
  default: deploy

- name:  Version
  type: string
  default: v0.0.0

- name:  PrivateRepository
  type: boolean
  default: false


- name:  AzureCustomFeed
  type: string
  default: a3dfeb18-d0fc-4033-99ae-50b8d724527b


stages:
  - stage: CI
    variables:
      - template: ../common/set_env_vars_params.yml  # Template reference
    displayName: CIStage
    jobs:
    - job: BuildApp
      steps:
      - template: ../common/install.yaml
      - template: ../common/build.yaml
        parameters:
          Environment: ${{ parameters.Environment }}
          RegionName: ${{ parameters.RegionName }}
          ServiceConnection: ${{ parameters.ServiceConnection }}
          Project: ${{ parameters.Project }}
          AppPath: ${{ parameters.AppPath }}
          ListLambdas: ${{ parameters.Listlambdas  }}
          Language: ${{ parameters.Language  }}
          PrivateRepository: ${{ parameters.PrivateRepository }}
          AzureCustomFeed: ${{ parameters.AzureCustomFeed }}
          CDKPath: ${{ parameters.CDKPath }}


  - stage: Deploy
    displayName: DeployStage${{ parameters.Environment }}

    jobs:
    - job: DeployApp
      steps:
      - checkout: none #skip checking out the default repository resource

      - template: ../common/install.yaml
      - template: ../common/deploy.yaml
        parameters: 
          Environment: ${{ parameters.Environment }}
          RegionName: ${{ parameters.RegionName }}
          ServiceConnection: ${{ parameters.ServiceConnection }}
          Project: ${{ parameters.Project }}
          Action: ${{ parameters.Action }}
          Language: ${{ parameters.Language }}
          PrivateRepository: ${{ parameters.PrivateRepository }}
          CDKPath: ${{ parameters.CDKPath }}
          OnDemandTestEnv: ${{ parameters.OnDemandTestEnv }}
          Version: ${{ parameters.Version }}
